version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-vendor
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - vendor-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-vendor
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - vendor-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-vendor
    environment:
      POSTGRES_DB: vendordb
      POSTGRES_USER: vendor
      POSTGRES_PASSWORD: vendor123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vendor-network

networks:
  vendor-network:
    driver: bridge

volumes:
  postgres_data:
